// src/runtime/RuntimeEmitters.js

/**
 * MLIR Builder'ın ihtiyaç duyduğu freestanding runtime şablonları:
 * (rts_strlen, rts_str_concat, rts_i64_to_str, rts_f64_to_str, rts_print_ptr,
 *  rts_union_*, Map/Set hash table, Channel, Arena/Pool/FixedBuffer allocators).
 */
export class RuntimeEmitters {
  static emitWasmHeap(usedFeatures) {
    let header = "";
    header += `  llvm.mlir.global external @__heap_base() : i8\n\n`;
    header += `  llvm.mlir.global internal @rts_heap_ptr() : !llvm.ptr {\n`;
    header += `    %0 = llvm.mlir.zero : !llvm.ptr\n`;
    header += `    llvm.return %0 : !llvm.ptr\n`;
    header += `  }\n\n`;

    header += `  llvm.func @malloc(%size: i64) -> !llvm.ptr {\n`;
    header += `    %g = llvm.mlir.addressof @rts_heap_ptr : !llvm.ptr\n`;
    header += `    %curr = llvm.load %g : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %null = llvm.mlir.zero : !llvm.ptr\n`;
    header += `    %is_null = llvm.icmp "eq" %curr, %null : !llvm.ptr\n`;
    header += `    llvm.cond_br %is_null, ^init_heap, ^have_heap(%curr : !llvm.ptr)\n`;
    header += `  ^init_heap:\n`;
    header += `    %base = llvm.mlir.addressof @__heap_base : !llvm.ptr\n`;
    header += `    llvm.br ^have_heap(%base : !llvm.ptr)\n`;
    header += `  ^have_heap(%ptr: !llvm.ptr):\n`;
    header += `    %c7 = llvm.mlir.constant(7 : i64) : i64\n`;
    header += `    %c8 = llvm.mlir.constant(8 : i64) : i64\n`;
    header += `    %s1 = llvm.add %size, %c7 : i64\n`;
    header += `    %rem = llvm.urem %s1, %c8 : i64\n`;
    header += `    %aligned = llvm.sub %s1, %rem : i64\n`;
    header += `    %next = llvm.getelementptr %ptr[%aligned] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `    llvm.store %next, %g : !llvm.ptr, !llvm.ptr\n`;
    header += `    llvm.return %ptr : !llvm.ptr\n`;
    header += `  }\n\n`;

    header += `  llvm.func @free(%ptr: !llvm.ptr) {\n`;
    header += `    llvm.return\n`;
    header += `  }\n\n`;

    header += `  llvm.func @calloc(%num: i64, %size: i64) -> !llvm.ptr {\n`;
    header += `    %total = llvm.mul %num, %size : i64\n`;
    header += `    %ptr = llvm.call @malloc(%total) : (i64) -> !llvm.ptr\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %c1 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `    %zero_byte = llvm.mlir.constant(0 : i8) : i8\n`;
    header += `    llvm.br ^loop(%c0 : i64)\n`;
    header += `  ^loop(%idx: i64):\n`;
    header += `    %cond = llvm.icmp "slt" %idx, %total : i64\n`;
    header += `    llvm.cond_br %cond, ^body, ^done\n`;
    header += `  ^body:\n`;
    header += `    %byte_ptr = llvm.getelementptr %ptr[%idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `    llvm.store %zero_byte, %byte_ptr : i8, !llvm.ptr\n`;
    header += `    %next_idx = llvm.add %idx, %c1 : i64\n`;
    header += `    llvm.br ^loop(%next_idx : i64)\n`;
    header += `  ^done:\n`;
    header += `    llvm.return %ptr : !llvm.ptr\n`;
    header += `  }\n\n`;

    if (usedFeatures.map) {
      header += `  llvm.func @strcmp(%s1: !llvm.ptr, %s2: !llvm.ptr) -> i32 {\n`;
      header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
      header += `    %c1 = llvm.mlir.constant(1 : i64) : i64\n`;
      header += `    %c0_i8 = llvm.mlir.constant(0 : i8) : i8\n`;
      header += `    %c0_i32 = llvm.mlir.constant(0 : i32) : i32\n`;
      header += `    llvm.br ^loop(%c0 : i64)\n`;
      header += `  ^loop(%idx: i64):\n`;
      header += `    %p1 = llvm.getelementptr %s1[%idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
      header += `    %p2 = llvm.getelementptr %s2[%idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
      header += `    %b1 = llvm.load %p1 : !llvm.ptr -> i8\n`;
      header += `    %b2 = llvm.load %p2 : !llvm.ptr -> i8\n`;
      header += `    %diff = llvm.sub %b1, %b2 : i8\n`;
      header += `    %is_diff = llvm.icmp "ne" %diff, %c0_i8 : i8\n`;
      header += `    %diff_i32 = llvm.sext %diff : i8 to i32\n`;
      header += `    llvm.cond_br %is_diff, ^ret(%diff_i32 : i32), ^check_null\n`;
      header += `  ^check_null:\n`;
      header += `    %is_end = llvm.icmp "eq" %b1, %c0_i8 : i8\n`;
      header += `    %next_idx = llvm.add %idx, %c1 : i64\n`;
      header += `    llvm.cond_br %is_end, ^ret(%c0_i32 : i32), ^loop(%next_idx : i64)\n`;
      header += `  ^ret(%res: i32):\n`;
      header += `    llvm.return %res : i32\n`;
      header += `  }\n\n`;
    }
    return header;
  }

  static emitStrings(usedFeatures) {
    if (!usedFeatures.strings && !usedFeatures.union) return "";
    let header = "";

    // 1. @rts_strlen (Korumalı, null pointer güvenli)
    header += `  func.func @rts_strlen(%arg0: !llvm.ptr) -> i64 {\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %c1 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `    %c0_i8 = llvm.mlir.constant(0 : i8) : i8\n`;
    header += `    %c1_i32 = arith.constant 1 : i32\n`;
    header += `    %null = llvm.mlir.zero : !llvm.ptr\n`;
    header += `    %is_null = llvm.icmp "eq" %arg0, %null : !llvm.ptr\n`;
    header += `    %idx_slot = llvm.alloca %c1_i32 x i64 : (i32) -> !llvm.ptr\n`;
    header += `    llvm.store %c0, %idx_slot : i64, !llvm.ptr\n`;
    header += `    scf.if %is_null {\n`;
    header += `    } else {\n`;
    header += `      scf.while : () -> () {\n`;
    header += `        %idx = llvm.load %idx_slot : !llvm.ptr -> i64\n`;
    header += `        %c_ptr = llvm.getelementptr %arg0[%idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `        %ch = llvm.load %c_ptr : !llvm.ptr -> i8\n`;
    header += `        %cond = arith.cmpi ne, %ch, %c0_i8 : i8\n`;
    header += `        scf.condition(%cond)\n`;
    header += `      } do {\n`;
    header += `      ^bb0:\n`;
    header += `        %idx = llvm.load %idx_slot : !llvm.ptr -> i64\n`;
    header += `        %next = arith.addi %idx, %c1 : i64\n`;
    header += `        llvm.store %next, %idx_slot : i64, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      }\n`;
    header += `    }\n`;
    header += `    %res = llvm.load %idx_slot : !llvm.ptr -> i64\n`;
    header += `    func.return %res : i64\n`;
    header += `  }\n\n`;

    // 2. @rts_str_concat
    header += `  func.func @rts_str_concat(%s1: !llvm.ptr, %s2: !llvm.ptr) -> !llvm.ptr {\n`;
    header += `    %len1 = func.call @rts_strlen(%s1) : (!llvm.ptr) -> i64\n`;
    header += `    %len2 = func.call @rts_strlen(%s2) : (!llvm.ptr) -> i64\n`;
    header += `    %c1 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %c1_i32 = arith.constant 1 : i32\n`;
    header += `    %tot1 = arith.addi %len1, %len2 : i64\n`;
    header += `    %tot = arith.addi %tot1, %c1 : i64\n`;
    header += `    %buf = llvm.call @malloc(%tot) : (i64) -> !llvm.ptr\n`;
    header += `    %i_slot = llvm.alloca %c1_i32 x i64 : (i32) -> !llvm.ptr\n`;
    header += `    llvm.store %c0, %i_slot : i64, !llvm.ptr\n`;
    header += `    scf.while : () -> () {\n`;
    header += `      %i = llvm.load %i_slot : !llvm.ptr -> i64\n`;
    header += `      %cond = arith.cmpi slt, %i, %len1 : i64\n`;
    header += `      scf.condition(%cond)\n`;
    header += `    } do {\n`;
    header += `    ^bb0:\n`;
    header += `      %i = llvm.load %i_slot : !llvm.ptr -> i64\n`;
    header += `      %src = llvm.getelementptr %s1[%i] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      %ch = llvm.load %src : !llvm.ptr -> i8\n`;
    header += `      %dst = llvm.getelementptr %buf[%i] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %ch, %dst : i8, !llvm.ptr\n`;
    header += `      %next = arith.addi %i, %c1 : i64\n`;
    header += `      llvm.store %next, %i_slot : i64, !llvm.ptr\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    llvm.store %c0, %i_slot : i64, !llvm.ptr\n`;
    header += `    scf.while : () -> () {\n`;
    header += `      %i = llvm.load %i_slot : !llvm.ptr -> i64\n`;
    header += `      %cond = arith.cmpi slt, %i, %len2 : i64\n`;
    header += `      scf.condition(%cond)\n`;
    header += `    } do {\n`;
    header += `    ^bb0:\n`;
    header += `      %i = llvm.load %i_slot : !llvm.ptr -> i64\n`;
    header += `      %src = llvm.getelementptr %s2[%i] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      %ch = llvm.load %src : !llvm.ptr -> i8\n`;
    header += `      %dst_idx = arith.addi %len1, %i : i64\n`;
    header += `      %dst = llvm.getelementptr %buf[%dst_idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %ch, %dst : i8, !llvm.ptr\n`;
    header += `      %next = arith.addi %i, %c1 : i64\n`;
    header += `      llvm.store %next, %i_slot : i64, !llvm.ptr\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %c0_i8 = llvm.mlir.constant(0 : i8) : i8\n`;
    header += `    %end_ptr = llvm.getelementptr %buf[%tot1] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `    llvm.store %c0_i8, %end_ptr : i8, !llvm.ptr\n`;
    header += `    func.return %buf : !llvm.ptr\n`;
    header += `  }\n\n`;

    // 3. @rts_i64_to_str (Freestanding itoa)
    header += `  func.func @rts_i64_to_str(%val: i64) -> !llvm.ptr {\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %c10 = llvm.mlir.constant(10 : i64) : i64\n`;
    header += `    %c48 = llvm.mlir.constant(48 : i8) : i8\n`;
    header += `    %c45 = llvm.mlir.constant(45 : i8) : i8\n`;
    header += `    %c0_i8 = llvm.mlir.constant(0 : i8) : i8\n`;
    header += `    %c32_i32 = arith.constant 32 : i32\n`;
    header += `    %c1_i32 = arith.constant 1 : i32\n`;
    header += `    %c1 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `    %stack_buf = llvm.alloca %c32_i32 x i8 : (i32) -> !llvm.ptr\n`;
    header += `    %pos_slot = llvm.alloca %c1_i32 x i64 : (i32) -> !llvm.ptr\n`;
    header += `    %c31 = llvm.mlir.constant(31 : i64) : i64\n`;
    header += `    llvm.store %c31, %pos_slot : i64, !llvm.ptr\n`;
    header += `    %term_ptr = llvm.getelementptr %stack_buf[%c31] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `    llvm.store %c0_i8, %term_ptr : i8, !llvm.ptr\n`;
    header += `    %is_zero = arith.cmpi eq, %val, %c0 : i64\n`;
    header += `    %res_zero = scf.if %is_zero -> (!llvm.ptr) {\n`;
    header += `      %c2 = llvm.mlir.constant(2 : i64) : i64\n`;
    header += `      %zbuf = llvm.call @malloc(%c2) : (i64) -> !llvm.ptr\n`;
    header += `      llvm.store %c48, %zbuf : i8, !llvm.ptr\n`;
    header += `      %p1 = llvm.getelementptr %zbuf[%c1] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %c0_i8, %p1 : i8, !llvm.ptr\n`;
    header += `      scf.yield %zbuf : !llvm.ptr\n`;
    header += `    } else {\n`;
    header += `      %is_neg = arith.cmpi slt, %val, %c0 : i64\n`;
    header += `      %abs_val = scf.if %is_neg -> (i64) {\n`;
    header += `        %neg = arith.subi %c0, %val : i64\n`;
    header += `        scf.yield %neg : i64\n`;
    header += `      } else {\n`;
    header += `        scf.yield %val : i64\n`;
    header += `      }\n`;
    header += `      %curr_slot = llvm.alloca %c1_i32 x i64 : (i32) -> !llvm.ptr\n`;
    header += `      llvm.store %abs_val, %curr_slot : i64, !llvm.ptr\n`;
    header += `      scf.while : () -> () {\n`;
    header += `        %curr = llvm.load %curr_slot : !llvm.ptr -> i64\n`;
    header += `        %cond = arith.cmpi ugt, %curr, %c0 : i64\n`;
    header += `        scf.condition(%cond)\n`;
    header += `      } do {\n`;
    header += `      ^bb0:\n`;
    header += `        %curr = llvm.load %curr_slot : !llvm.ptr -> i64\n`;
    header += `        %rem = arith.remui %curr, %c10 : i64\n`;
    header += `        %next = arith.divui %curr, %c10 : i64\n`;
    header += `        llvm.store %next, %curr_slot : i64, !llvm.ptr\n`;
    header += `        %pos = llvm.load %pos_slot : !llvm.ptr -> i64\n`;
    header += `        %new_pos = arith.subi %pos, %c1 : i64\n`;
    header += `        llvm.store %new_pos, %pos_slot : i64, !llvm.ptr\n`;
    header += `        %rem_i8 = arith.trunci %rem : i64 to i8\n`;
    header += `        %digit = arith.addi %rem_i8, %c48 : i8\n`;
    header += `        %d_ptr = llvm.getelementptr %stack_buf[%new_pos] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `        llvm.store %digit, %d_ptr : i8, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      }\n`;
    header += `      scf.if %is_neg {\n`;
    header += `        %pos = llvm.load %pos_slot : !llvm.ptr -> i64\n`;
    header += `        %new_pos = arith.subi %pos, %c1 : i64\n`;
    header += `        llvm.store %new_pos, %pos_slot : i64, !llvm.ptr\n`;
    header += `        %minus_ptr = llvm.getelementptr %stack_buf[%new_pos] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `        llvm.store %c45, %minus_ptr : i8, !llvm.ptr\n`;
    header += `      }\n`;
    header += `      %final_pos = llvm.load %pos_slot : !llvm.ptr -> i64\n`;
    header += `      %len = arith.subi %c31, %final_pos : i64\n`;
    header += `      %buf_sz = arith.addi %len, %c1 : i64\n`;
    header += `      %out_buf = llvm.call @malloc(%buf_sz) : (i64) -> !llvm.ptr\n`;
    header += `      %copy_slot = llvm.alloca %c1_i32 x i64 : (i32) -> !llvm.ptr\n`;
    header += `      llvm.store %c0, %copy_slot : i64, !llvm.ptr\n`;
    header += `      scf.while : () -> () {\n`;
    header += `        %ci = llvm.load %copy_slot : !llvm.ptr -> i64\n`;
    header += `        %c_cond = arith.cmpi slt, %ci, %buf_sz : i64\n`;
    header += `        scf.condition(%c_cond)\n`;
    header += `      } do {\n`;
    header += `      ^bb0:\n`;
    header += `        %ci = llvm.load %copy_slot : !llvm.ptr -> i64\n`;
    header += `        %src_idx = arith.addi %final_pos, %ci : i64\n`;
    header += `        %sp = llvm.getelementptr %stack_buf[%src_idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `        %b = llvm.load %sp : !llvm.ptr -> i8\n`;
    header += `        %dp = llvm.getelementptr %out_buf[%ci] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `        llvm.store %b, %dp : i8, !llvm.ptr\n`;
    header += `        %next_ci = arith.addi %ci, %c1 : i64\n`;
    header += `        llvm.store %next_ci, %copy_slot : i64, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      }\n`;
    header += `      scf.yield %out_buf : !llvm.ptr\n`;
    header += `    }\n`;
    header += `    func.return %res_zero : !llvm.ptr\n`;
    header += `  }\n\n`;

    // 4. @rts_f64_to_str (Freestanding dtoa - Sabit Nokta / Yuvarlama düzeltmeli)
    header += `  func.func @rts_f64_to_str(%val: f64) -> !llvm.ptr {\n`;
    header += `    %c0_f64 = arith.constant 0.0 : f64\n`;
    header += `    %is_neg = arith.cmpf olt, %val, %c0_f64 : f64\n`;
    header += `    %abs_val = scf.if %is_neg -> (f64) {\n`;
    header += `      %neg = arith.subf %c0_f64, %val : f64\n`;
    header += `      scf.yield %neg : f64\n`;
    header += `    } else {\n`;
    header += `      scf.yield %val : f64\n`;
    header += `    }\n`;
    header += `    %c_round = arith.constant 0.00005 : f64\n`;
    header += `    %rounded_val = arith.addf %abs_val, %c_round : f64\n`;
    header += `    %int_part = arith.fptosi %rounded_val : f64 to i64\n`;
    header += `    %int_f64 = arith.sitofp %int_part : i64 to f64\n`;
    header += `    %frac_f64 = arith.subf %rounded_val, %int_f64 : f64\n`;
    header += `    %c10000 = arith.constant 10000.0 : f64\n`;
    header += `    %frac_x = arith.mulf %frac_f64, %c10000 : f64\n`;
    header += `    %frac_part = arith.fptosi %frac_x : f64 to i64\n`;
    header += `    %s_int_raw = func.call @rts_i64_to_str(%int_part) : (i64) -> !llvm.ptr\n`;
    header += `    %s_int = scf.if %is_neg -> (!llvm.ptr) {\n`;
    header += `      %c2 = llvm.mlir.constant(2 : i64) : i64\n`;
    header += `      %c1_i64 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `      %minus_buf = llvm.call @malloc(%c2) : (i64) -> !llvm.ptr\n`;
    header += `      %c45 = llvm.mlir.constant(45 : i8) : i8\n`;
    header += `      %c0_i8 = llvm.mlir.constant(0 : i8) : i8\n`;
    header += `      llvm.store %c45, %minus_buf : i8, !llvm.ptr\n`;
    header += `      %p_null = llvm.getelementptr %minus_buf[%c1_i64] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %c0_i8, %p_null : i8, !llvm.ptr\n`;
    header += `      %neg_s = func.call @rts_str_concat(%minus_buf, %s_int_raw) : (!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n`;
    header += `      scf.yield %neg_s : !llvm.ptr\n`;
    header += `    } else {\n`;
    header += `      scf.yield %s_int_raw : !llvm.ptr\n`;
    header += `    }\n`;
    header += `    %c0_i64 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %has_no_frac = arith.cmpi eq, %frac_part, %c0_i64 : i64\n`;
    header += `    %res = scf.if %has_no_frac -> (!llvm.ptr) {\n`;
    header += `      %c8_i64 = llvm.mlir.constant(8 : i64) : i64\n`;
    header += `      %zero_frac_buf = llvm.call @malloc(%c8_i64) : (i64) -> !llvm.ptr\n`;
    header += `      %dot = llvm.mlir.constant(46 : i8) : i8\n`;
    header += `      %zero_ch = llvm.mlir.constant(48 : i8) : i8\n`;
    header += `      %null_ch = llvm.mlir.constant(0 : i8) : i8\n`;
    header += `      llvm.store %dot, %zero_frac_buf : i8, !llvm.ptr\n`;
    header += `      %c1_idx = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `      %c2_idx = llvm.mlir.constant(2 : i64) : i64\n`;
    header += `      %c3_idx = llvm.mlir.constant(3 : i64) : i64\n`;
    header += `      %c4_idx = llvm.mlir.constant(4 : i64) : i64\n`;
    header += `      %c5_idx = llvm.mlir.constant(5 : i64) : i64\n`;
    header += `      %c6_idx = llvm.mlir.constant(6 : i64) : i64\n`;
    header += `      %c7_idx = llvm.mlir.constant(7 : i64) : i64\n`;
    header += `      %p_z1 = llvm.getelementptr %zero_frac_buf[%c1_idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %zero_ch, %p_z1 : i8, !llvm.ptr\n`;
    header += `      %p_z2 = llvm.getelementptr %zero_frac_buf[%c2_idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %zero_ch, %p_z2 : i8, !llvm.ptr\n`;
    header += `      %p_z3 = llvm.getelementptr %zero_frac_buf[%c3_idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %zero_ch, %p_z3 : i8, !llvm.ptr\n`;
    header += `      %p_z4 = llvm.getelementptr %zero_frac_buf[%c4_idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %zero_ch, %p_z4 : i8, !llvm.ptr\n`;
    header += `      %p_z5 = llvm.getelementptr %zero_frac_buf[%c5_idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %zero_ch, %p_z5 : i8, !llvm.ptr\n`;
    header += `      %p_z6 = llvm.getelementptr %zero_frac_buf[%c6_idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %zero_ch, %p_z6 : i8, !llvm.ptr\n`;
    header += `      %p_z7 = llvm.getelementptr %zero_frac_buf[%c7_idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %null_ch, %p_z7 : i8, !llvm.ptr\n`;
    header += `      %zero_res = func.call @rts_str_concat(%s_int, %zero_frac_buf) : (!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n`;
    header += `      scf.yield %zero_res : !llvm.ptr\n`;
    header += `    } else {\n`;
    header += `      %c6_i64 = llvm.mlir.constant(6 : i64) : i64\n`;
    header += `      %frac_buf = llvm.call @malloc(%c6_i64) : (i64) -> !llvm.ptr\n`;
    header += `      %dot = llvm.mlir.constant(46 : i8) : i8\n`;
    header += `      llvm.store %dot, %frac_buf : i8, !llvm.ptr\n`;
    header += `      %c1_i32 = arith.constant 1 : i32\n`;
    header += `      %rem_slot = llvm.alloca %c1_i32 x i64 : (i32) -> !llvm.ptr\n`;
    header += `      llvm.store %frac_part, %rem_slot : i64, !llvm.ptr\n`;
    header += `      %idx_slot = llvm.alloca %c1_i32 x i64 : (i32) -> !llvm.ptr\n`;
    header += `      %c4_i64 = llvm.mlir.constant(4 : i64) : i64\n`;
    header += `      llvm.store %c4_i64, %idx_slot : i64, !llvm.ptr\n`;
    header += `      %c10_i64 = llvm.mlir.constant(10 : i64) : i64\n`;
    header += `      %c48_i8 = llvm.mlir.constant(48 : i8) : i8\n`;
    header += `      %c0_i8 = llvm.mlir.constant(0 : i8) : i8\n`;
    header += `      %c1_i64 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `      scf.while : () -> () {\n`;
    header += `        %idx = llvm.load %idx_slot : !llvm.ptr -> i64\n`;
    header += `        %cond = arith.cmpi sgt, %idx, %c0_i64 : i64\n`;
    header += `        scf.condition(%cond)\n`;
    header += `      } do {\n`;
    header += `      ^bb0:\n`;
    header += `        %rem = llvm.load %rem_slot : !llvm.ptr -> i64\n`;
    header += `        %digit_val = arith.remui %rem, %c10_i64 : i64\n`;
    header += `        %next_rem = arith.divui %rem, %c10_i64 : i64\n`;
    header += `        llvm.store %next_rem, %rem_slot : i64, !llvm.ptr\n`;
    header += `        %d_tr = arith.trunci %digit_val : i64 to i8\n`;
    header += `        %ch = arith.addi %d_tr, %c48_i8 : i8\n`;
    header += `        %idx = llvm.load %idx_slot : !llvm.ptr -> i64\n`;
    header += `        %pos = llvm.getelementptr %frac_buf[%idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `        llvm.store %ch, %pos : i8, !llvm.ptr\n`;
    header += `        %next_idx = arith.subi %idx, %c1_i64 : i64\n`;
    header += `        llvm.store %next_idx, %idx_slot : i64, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      }\n`;
    header += `      %c5_i64 = llvm.mlir.constant(5 : i64) : i64\n`;
    header += `      %term = llvm.getelementptr %frac_buf[%c5_i64] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %c0_i8, %term : i8, !llvm.ptr\n`;
    header += `      %full = func.call @rts_str_concat(%s_int, %frac_buf) : (!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n`;
    header += `      scf.yield %full : !llvm.ptr\n`;
    header += `    }\n`;
    header += `    func.return %res : !llvm.ptr\n`;
    header += `  }\n\n`;

    return header;
  }

  static emitPrintf(usedFeatures, symTrue, symFalse) {
    if (!usedFeatures.printf) return "";
    let header = "";

    header += `  func.func @rts_print_f64(%arg0: f64) {\n`;
    header += `    %fmt = llvm.mlir.addressof @fmt_f64 : !llvm.ptr\n`;
    header += `    llvm.call @printf(%fmt, %arg0) {var_callee_type = !llvm.func<i32 (!llvm.ptr, ...)>} : (!llvm.ptr, f64) -> i32\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_print_i32(%arg0: i32) {\n`;
    header += `    %fmt = llvm.mlir.addressof @fmt_i32 : !llvm.ptr\n`;
    header += `    llvm.call @printf(%fmt, %arg0) {var_callee_type = !llvm.func<i32 (!llvm.ptr, ...)>} : (!llvm.ptr, i32) -> i32\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_print_i64(%arg0: i64) {\n`;
    header += `    %fmt = llvm.mlir.addressof @fmt_i64 : !llvm.ptr\n`;
    header += `    llvm.call @printf(%fmt, %arg0) {var_callee_type = !llvm.func<i32 (!llvm.ptr, ...)>} : (!llvm.ptr, i64) -> i32\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_print_str(%arg0: !llvm.ptr) {\n`;
    header += `    %fmt = llvm.mlir.addressof @fmt_str : !llvm.ptr\n`;
    header += `    llvm.call @printf(%fmt, %arg0) {var_callee_type = !llvm.func<i32 (!llvm.ptr, ...)>} : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_print_ptr(%arg0: !llvm.ptr) {\n`;
    header += `    %fmt = llvm.mlir.addressof @fmt_ptr : !llvm.ptr\n`;
    header += `    llvm.call @printf(%fmt, %arg0) {var_callee_type = !llvm.func<i32 (!llvm.ptr, ...)>} : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_print_bool(%arg0: i1) {\n`;
    header += `    %str_t = llvm.mlir.addressof ${symTrue} : !llvm.ptr\n`;
    header += `    %str_f = llvm.mlir.addressof ${symFalse} : !llvm.ptr\n`;
    header += `    %fmt = llvm.mlir.addressof @fmt_str : !llvm.ptr\n`;
    header += `    %c1 = arith.constant 1 : i32\n`;
    header += `    %slot = llvm.alloca %c1 x !llvm.ptr : (i32) -> !llvm.ptr\n`;
    header += `    scf.if %arg0 {\n`;
    header += `      llvm.store %str_t, %slot : !llvm.ptr, !llvm.ptr\n`;
    header += `      scf.yield\n`;
    header += `    } else {\n`;
    header += `      llvm.store %str_f, %slot : !llvm.ptr, !llvm.ptr\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %val = llvm.load %slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `    llvm.call @printf(%fmt, %val) {var_callee_type = !llvm.func<i32 (!llvm.ptr, ...)>} : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_print_space() {\n`;
    header += `    %fmt = llvm.mlir.addressof @fmt_space : !llvm.ptr\n`;
    header += `    llvm.call @printf(%fmt) {var_callee_type = !llvm.func<i32 (!llvm.ptr, ...)>} : (!llvm.ptr) -> i32\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_print_newline() {\n`;
    header += `    %fmt = llvm.mlir.addressof @fmt_nl : !llvm.ptr\n`;
    header += `    llvm.call @printf(%fmt) {var_callee_type = !llvm.func<i32 (!llvm.ptr, ...)>} : (!llvm.ptr) -> i32\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    return header;
  }

  static emitUnion(usedFeatures, symNumber, symString, symBoolean, symObject) {
    if (!usedFeatures.union) return "";
    let header = "";

    header += `  func.func @rts_union_typeof(%arg0: !llvm.ptr) -> !llvm.ptr {\n`;
    header += `    %tag_ptr = llvm.getelementptr %arg0[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i32, i64)>\n`;
    header += `    %tag = llvm.load %tag_ptr : !llvm.ptr -> i32\n`;
    header += `    %c1 = arith.constant 1 : i32\n`;
    header += `    %c2 = arith.constant 2 : i32\n`;
    header += `    %c3 = arith.constant 3 : i32\n`;
    header += `    %c4 = arith.constant 4 : i32\n`;
    header += `    %str_num = llvm.mlir.addressof ${symNumber} : !llvm.ptr\n`;
    header += `    %str_str = llvm.mlir.addressof ${symString} : !llvm.ptr\n`;
    header += `    %str_bool = llvm.mlir.addressof ${symBoolean} : !llvm.ptr\n`;
    header += `    %str_obj = llvm.mlir.addressof ${symObject} : !llvm.ptr\n`;
    header += `    %res_slot = llvm.alloca %c1 x !llvm.ptr : (i32) -> !llvm.ptr\n`;
    header += `    llvm.store %str_obj, %res_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `    %is_i64 = arith.cmpi eq, %tag, %c1 : i32\n`;
    header += `    %is_f64 = arith.cmpi eq, %tag, %c2 : i32\n`;
    header += `    %is_num = arith.ori %is_i64, %is_f64 : i1\n`;
    header += `    scf.if %is_num {\n`;
    header += `      llvm.store %str_num, %res_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `      scf.yield\n`;
    header += `    } else {\n`;
    header += `      %is_str = arith.cmpi eq, %tag, %c3 : i32\n`;
    header += `      scf.if %is_str {\n`;
    header += `        llvm.store %str_str, %res_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      } else {\n`;
    header += `        %is_b = arith.cmpi eq, %tag, %c4 : i32\n`;
    header += `        scf.if %is_b {\n`;
    header += `          llvm.store %str_bool, %res_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `          scf.yield\n`;
    header += `        }\n`;
    header += `        scf.yield\n`;
    header += `      }\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %res = llvm.load %res_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `    func.return %res : !llvm.ptr\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_union_get_number(%arg0: !llvm.ptr) -> f64 {\n`;
    header += `    %tag_ptr = llvm.getelementptr %arg0[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i32, i64)>\n`;
    header += `    %tag = llvm.load %tag_ptr : !llvm.ptr -> i32\n`;
    header += `    %payload_ptr = llvm.getelementptr %arg0[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i32, i64)>\n`;
    header += `    %c1 = arith.constant 1 : i32\n`;
    header += `    %is_int = arith.cmpi eq, %tag, %c1 : i32\n`;
    header += `    %res_slot = llvm.alloca %c1 x f64 : (i32) -> !llvm.ptr\n`;
    header += `    scf.if %is_int {\n`;
    header += `      %ival = llvm.load %payload_ptr : !llvm.ptr -> i64\n`;
    header += `      %fval = arith.sitofp %ival : i64 to f64\n`;
    header += `      llvm.store %fval, %res_slot : f64, !llvm.ptr\n`;
    header += `      scf.yield\n`;
    header += `    } else {\n`;
    header += `      %fval2 = llvm.load %payload_ptr : !llvm.ptr -> f64\n`;
    header += `      llvm.store %fval2, %res_slot : f64, !llvm.ptr\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %res = llvm.load %res_slot : !llvm.ptr -> f64\n`;
    header += `    func.return %res : f64\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_union_get_string(%arg0: !llvm.ptr) -> !llvm.ptr {\n`;
    header += `    %payload_ptr = llvm.getelementptr %arg0[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i32, i64)>\n`;
    header += `    %str = llvm.load %payload_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `    func.return %str : !llvm.ptr\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_union_get_bool(%arg0: !llvm.ptr) -> i1 {\n`;
    header += `    %payload_ptr = llvm.getelementptr %arg0[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i32, i64)>\n`;
    header += `    %b = llvm.load %payload_ptr : !llvm.ptr -> i1\n`;
    header += `    func.return %b : i1\n`;
    header += `  }\n\n`;

    if (usedFeatures.printf) {
      header += `  func.func @rts_print_union(%arg0: !llvm.ptr) {\n`;
      header += `    %tag_ptr = llvm.getelementptr %arg0[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i32, i64)>\n`;
      header += `    %tag = llvm.load %tag_ptr : !llvm.ptr -> i32\n`;
      header += `    %payload_ptr = llvm.getelementptr %arg0[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i32, i64)>\n`;
      header += `    %c1 = arith.constant 1 : i32\n`;
      header += `    %c2 = arith.constant 2 : i32\n`;
      header += `    %c3 = arith.constant 3 : i32\n`;
      header += `    %is_i64 = arith.cmpi eq, %tag, %c1 : i32\n`;
      header += `    scf.if %is_i64 {\n`;
      header += `      %ival = llvm.load %payload_ptr : !llvm.ptr -> i64\n`;
      header += `      func.call @rts_print_i64(%ival) : (i64) -> ()\n`;
      header += `      scf.yield\n`;
      header += `    } else {\n`;
      header += `      %is_f64 = arith.cmpi eq, %tag, %c2 : i32\n`;
      header += `      scf.if %is_f64 {\n`;
      header += `        %fval = llvm.load %payload_ptr : !llvm.ptr -> f64\n`;
      header += `        func.call @rts_print_f64(%fval) : (f64) -> ()\n`;
      header += `        scf.yield\n`;
      header += `      } else {\n`;
      header += `        %is_str = arith.cmpi eq, %tag, %c3 : i32\n`;
      header += `        scf.if %is_str {\n`;
      header += `          %strval = llvm.load %payload_ptr : !llvm.ptr -> !llvm.ptr\n`;
      header += `          func.call @rts_print_str(%strval) : (!llvm.ptr) -> ()\n`;
      header += `          scf.yield\n`;
      header += `        } else {\n`;
      header += `          %bval = llvm.load %payload_ptr : !llvm.ptr -> i64\n`;
      header += `          func.call @rts_print_i64(%bval) : (i64) -> ()\n`;
      header += `          scf.yield\n`;
      header += `        }\n`;
      header += `      }\n`;
      header += `      scf.yield\n`;
      header += `    }\n`;
      header += `    func.return\n`;
      header += `  }\n\n`;
    }

    header += `  func.func @rts_union_to_string(%arg0: !llvm.ptr) -> !llvm.ptr {\n`;
    header += `    %tag_ptr = llvm.getelementptr %arg0[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i32, i64)>\n`;
    header += `    %tag = llvm.load %tag_ptr : !llvm.ptr -> i32\n`;
    header += `    %payload_ptr = llvm.getelementptr %arg0[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i32, i64)>\n`;
    header += `    %c1 = arith.constant 1 : i32\n`;
    header += `    %c2 = arith.constant 2 : i32\n`;
    header += `    %c3 = arith.constant 3 : i32\n`;
    header += `    %res_slot = llvm.alloca %c1 x !llvm.ptr : (i32) -> !llvm.ptr\n`;
    header += `    %is_i64 = arith.cmpi eq, %tag, %c1 : i32\n`;
    header += `    scf.if %is_i64 {\n`;
    header += `      %ival = llvm.load %payload_ptr : !llvm.ptr -> i64\n`;
    header += `      %str = func.call @rts_i64_to_str(%ival) : (i64) -> !llvm.ptr\n`;
    header += `      llvm.store %str, %res_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `      scf.yield\n`;
    header += `    } else {\n`;
    header += `      %is_f64 = arith.cmpi eq, %tag, %c2 : i32\n`;
    header += `      scf.if %is_f64 {\n`;
    header += `        %fval = llvm.load %payload_ptr : !llvm.ptr -> f64\n`;
    header += `        %str = func.call @rts_f64_to_str(%fval) : (f64) -> !llvm.ptr\n`;
    header += `        llvm.store %str, %res_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `      } else {\n`;
    header += `        %is_str = arith.cmpi eq, %tag, %c3 : i32\n`;
    header += `        scf.if %is_str {\n`;
    header += `          %strval = llvm.load %payload_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `          llvm.store %strval, %res_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        } else {\n`;
    header += `          %bval = llvm.load %payload_ptr : !llvm.ptr -> i64\n`;
    header += `          %str = func.call @rts_i64_to_str(%bval) : (i64) -> !llvm.ptr\n`;
    header += `          llvm.store %str, %res_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        }\n`;
    header += `      }\n`;
    header += `    }\n`;
    header += `    %final_str = llvm.load %res_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `    func.return %final_str : !llvm.ptr\n`;
    header += `  }\n\n`;

    return header;
  }

  static emitMapSet(usedFeatures) {
    if (!usedFeatures.map) return "";
    let header = "";

    header += `  func.func @rts_hash_str(%arg0: !llvm.ptr) -> i64 {\n`;
    header += `    %c5381 = llvm.mlir.constant(5381 : i64) : i64\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %c1 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `    %c5 = llvm.mlir.constant(5 : i64) : i64\n`;
    header += `    %c0_i8 = llvm.mlir.constant(0 : i8) : i8\n`;
    header += `    %c1_i32 = arith.constant 1 : i32\n`;
    header += `    %h_slot = llvm.alloca %c1_i32 x i64 : (i32) -> !llvm.ptr\n`;
    header += `    llvm.store %c5381, %h_slot : i64, !llvm.ptr\n`;
    header += `    %idx_slot = llvm.alloca %c1_i32 x i64 : (i32) -> !llvm.ptr\n`;
    header += `    llvm.store %c0, %idx_slot : i64, !llvm.ptr\n`;
    header += `    scf.while : () -> () {\n`;
    header += `      %idx = llvm.load %idx_slot : !llvm.ptr -> i64\n`;
    header += `      %c_ptr = llvm.getelementptr %arg0[%idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      %ch = llvm.load %c_ptr : !llvm.ptr -> i8\n`;
    header += `      %cond = arith.cmpi ne, %ch, %c0_i8 : i8\n`;
    header += `      scf.condition(%cond)\n`;
    header += `    } do {\n`;
    header += `    ^bb0:\n`;
    header += `      %idx = llvm.load %idx_slot : !llvm.ptr -> i64\n`;
    header += `      %c_ptr = llvm.getelementptr %arg0[%idx] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      %ch = llvm.load %c_ptr : !llvm.ptr -> i8\n`;
    header += `      %ch_i64 = arith.extui %ch : i8 to i64\n`;
    header += `      %h = llvm.load %h_slot : !llvm.ptr -> i64\n`;
    header += `      %h_shl = arith.shli %h, %c5 : i64\n`;
    header += `      %h_add = arith.addi %h_shl, %h : i64\n`;
    header += `      %new_h = arith.addi %h_add, %ch_i64 : i64\n`;
    header += `      llvm.store %new_h, %h_slot : i64, !llvm.ptr\n`;
    header += `      %next_idx = arith.addi %idx, %c1 : i64\n`;
    header += `      llvm.store %next_idx, %idx_slot : i64, !llvm.ptr\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %res = llvm.load %h_slot : !llvm.ptr -> i64\n`;
    header += `    func.return %res : i64\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_map_new() -> !llvm.ptr {\n`;
    header += `    %sz_map = llvm.mlir.constant(24 : i64) : i64\n`;
    header += `    %map = llvm.call @malloc(%sz_map) : (i64) -> !llvm.ptr\n`;
    header += `    %cap = llvm.mlir.constant(64 : i64) : i64\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %cap_ptr = llvm.getelementptr %map[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    llvm.store %cap, %cap_ptr : i64, !llvm.ptr\n`;
    header += `    %sz_ptr = llvm.getelementptr %map[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    llvm.store %c0, %sz_ptr : i64, !llvm.ptr\n`;
    header += `    %c8 = llvm.mlir.constant(8 : i64) : i64\n`;
    header += `    %buckets = llvm.call @calloc(%cap, %c8) : (i64, i64) -> !llvm.ptr\n`;
    header += `    %buckets_ptr = llvm.getelementptr %map[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    llvm.store %buckets, %buckets_ptr : !llvm.ptr, !llvm.ptr\n`;
    header += `    func.return %map : !llvm.ptr\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_map_set_str_f64(%map: !llvm.ptr, %key: !llvm.ptr, %val: f64) {\n`;
    header += `    %cap_ptr = llvm.getelementptr %map[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    %cap = llvm.load %cap_ptr : !llvm.ptr -> i64\n`;
    header += `    %buckets_ptr = llvm.getelementptr %map[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    %buckets = llvm.load %buckets_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %h = func.call @rts_hash_str(%key) : (!llvm.ptr) -> i64\n`;
    header += `    %b_idx = arith.remui %h, %cap : i64\n`;
    header += `    %bucket_slot = llvm.getelementptr %buckets[%b_idx] : (!llvm.ptr, i64) -> !llvm.ptr, !llvm.ptr\n`;
    header += `    %c1_i32 = arith.constant 1 : i32\n`;
    header += `    %curr_slot = llvm.alloca %c1_i32 x !llvm.ptr : (i32) -> !llvm.ptr\n`;
    header += `    %init_head = llvm.load %bucket_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `    llvm.store %init_head, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `    %null_ptr = llvm.mlir.zero : !llvm.ptr\n`;
    header += `    %c0_i32 = arith.constant 0 : i32\n`;
    header += `    %found_slot = llvm.alloca %c1_i32 x i1 : (i32) -> !llvm.ptr\n`;
    header += `    %false_val = arith.constant false\n`;
    header += `    llvm.store %false_val, %found_slot : i1, !llvm.ptr\n`;
    header += `    scf.while : () -> () {\n`;
    header += `      %curr = llvm.load %curr_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %has_curr = llvm.icmp "ne" %curr, %null_ptr : !llvm.ptr\n`;
    header += `      scf.condition(%has_curr)\n`;
    header += `    } do {\n`;
    header += `    ^bb0:\n`;
    header += `      %curr = llvm.load %curr_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %k_ptr = llvm.getelementptr %curr[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `      %curr_key = llvm.load %k_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %cmp = llvm.call @strcmp(%curr_key, %key) : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `      %is_eq = arith.cmpi eq, %cmp, %c0_i32 : i32\n`;
    header += `      scf.if %is_eq {\n`;
    header += `        %v_ptr = llvm.getelementptr %curr[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `        llvm.store %val, %v_ptr : f64, !llvm.ptr\n`;
    header += `        %true_val = arith.constant true\n`;
    header += `        llvm.store %true_val, %found_slot : i1, !llvm.ptr\n`;
    header += `        llvm.store %null_ptr, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      } else {\n`;
    header += `        %next_ptr = llvm.getelementptr %curr[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `        %next = llvm.load %next_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `        llvm.store %next, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      }\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %found = llvm.load %found_slot : !llvm.ptr -> i1\n`;
    header += `    scf.if %found {\n`;
    header += `    } else {\n`;
    header += `      %sz_entry = llvm.mlir.constant(32 : i64) : i64\n`;
    header += `      %new_node = llvm.call @malloc(%sz_entry) : (i64) -> !llvm.ptr\n`;
    header += `      %head_now = llvm.load %bucket_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %p_next = llvm.getelementptr %new_node[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `      llvm.store %head_now, %p_next : !llvm.ptr, !llvm.ptr\n`;
    header += `      %p_key = llvm.getelementptr %new_node[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `      llvm.store %key, %p_key : !llvm.ptr, !llvm.ptr\n`;
    header += `      %p_val = llvm.getelementptr %new_node[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `      llvm.store %val, %p_val : f64, !llvm.ptr\n`;
    header += `      llvm.store %new_node, %bucket_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `      %sz_ptr = llvm.getelementptr %map[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `      %sz_now = llvm.load %sz_ptr : !llvm.ptr -> i64\n`;
    header += `      %c1 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `      %new_sz = arith.addi %sz_now, %c1 : i64\n`;
    header += `      llvm.store %new_sz, %sz_ptr : i64, !llvm.ptr\n`;
    header += `    }\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_map_set_str_ptr(%map: !llvm.ptr, %key: !llvm.ptr, %val: !llvm.ptr) {\n`;
    header += `    %cap_ptr = llvm.getelementptr %map[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    %cap = llvm.load %cap_ptr : !llvm.ptr -> i64\n`;
    header += `    %buckets_ptr = llvm.getelementptr %map[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    %buckets = llvm.load %buckets_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %h = func.call @rts_hash_str(%key) : (!llvm.ptr) -> i64\n`;
    header += `    %b_idx = arith.remui %h, %cap : i64\n`;
    header += `    %bucket_slot = llvm.getelementptr %buckets[%b_idx] : (!llvm.ptr, i64) -> !llvm.ptr, !llvm.ptr\n`;
    header += `    %c1_i32 = arith.constant 1 : i32\n`;
    header += `    %curr_slot = llvm.alloca %c1_i32 x !llvm.ptr : (i32) -> !llvm.ptr\n`;
    header += `    %init_head = llvm.load %bucket_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `    llvm.store %init_head, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `    %null_ptr = llvm.mlir.zero : !llvm.ptr\n`;
    header += `    %c0_i32 = arith.constant 0 : i32\n`;
    header += `    %found_slot = llvm.alloca %c1_i32 x i1 : (i32) -> !llvm.ptr\n`;
    header += `    %false_val = arith.constant false\n`;
    header += `    llvm.store %false_val, %found_slot : i1, !llvm.ptr\n`;
    header += `    scf.while : () -> () {\n`;
    header += `      %curr = llvm.load %curr_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %has_curr = llvm.icmp "ne" %curr, %null_ptr : !llvm.ptr\n`;
    header += `      scf.condition(%has_curr)\n`;
    header += `    } do {\n`;
    header += `    ^bb0:\n`;
    header += `      %curr = llvm.load %curr_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %k_ptr = llvm.getelementptr %curr[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `      %curr_key = llvm.load %k_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %cmp = llvm.call @strcmp(%curr_key, %key) : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `      %is_eq = arith.cmpi eq, %cmp, %c0_i32 : i32\n`;
    header += `      scf.if %is_eq {\n`;
    header += `        %v_ptr = llvm.getelementptr %curr[0, 3] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `        llvm.store %val, %v_ptr : !llvm.ptr, !llvm.ptr\n`;
    header += `        %true_val = arith.constant true\n`;
    header += `        llvm.store %true_val, %found_slot : i1, !llvm.ptr\n`;
    header += `        llvm.store %null_ptr, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      } else {\n`;
    header += `        %next_ptr = llvm.getelementptr %curr[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `        %next = llvm.load %next_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `        llvm.store %next, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      }\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %found = llvm.load %found_slot : !llvm.ptr -> i1\n`;
    header += `    scf.if %found {\n`;
    header += `    } else {\n`;
    header += `      %sz_entry = llvm.mlir.constant(32 : i64) : i64\n`;
    header += `      %new_node = llvm.call @malloc(%sz_entry) : (i64) -> !llvm.ptr\n`;
    header += `      %head_now = llvm.load %bucket_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %p_next = llvm.getelementptr %new_node[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `      llvm.store %head_now, %p_next : !llvm.ptr, !llvm.ptr\n`;
    header += `      %p_key = llvm.getelementptr %new_node[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `      llvm.store %key, %p_key : !llvm.ptr, !llvm.ptr\n`;
    header += `      %p_val = llvm.getelementptr %new_node[0, 3] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `      llvm.store %val, %p_val : !llvm.ptr, !llvm.ptr\n`;
    header += `      llvm.store %new_node, %bucket_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `      %sz_ptr = llvm.getelementptr %map[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `      %sz_now = llvm.load %sz_ptr : !llvm.ptr -> i64\n`;
    header += `      %c1 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `      %new_sz = arith.addi %sz_now, %c1 : i64\n`;
    header += `      llvm.store %new_sz, %sz_ptr : i64, !llvm.ptr\n`;
    header += `    }\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_map_get_str_f64(%map: !llvm.ptr, %key: !llvm.ptr) -> f64 {\n`;
    header += `    %cap_ptr = llvm.getelementptr %map[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    %cap = llvm.load %cap_ptr : !llvm.ptr -> i64\n`;
    header += `    %buckets_ptr = llvm.getelementptr %map[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    %buckets = llvm.load %buckets_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %h = func.call @rts_hash_str(%key) : (!llvm.ptr) -> i64\n`;
    header += `    %b_idx = arith.remui %h, %cap : i64\n`;
    header += `    %bucket_slot = llvm.getelementptr %buckets[%b_idx] : (!llvm.ptr, i64) -> !llvm.ptr, !llvm.ptr\n`;
    header += `    %c1_i32 = arith.constant 1 : i32\n`;
    header += `    %curr_slot = llvm.alloca %c1_i32 x !llvm.ptr : (i32) -> !llvm.ptr\n`;
    header += `    %init_head = llvm.load %bucket_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `    llvm.store %init_head, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `    %res_slot = llvm.alloca %c1_i32 x f64 : (i32) -> !llvm.ptr\n`;
    header += `    %c0_f64 = arith.constant 0.0 : f64\n`;
    header += `    llvm.store %c0_f64, %res_slot : f64, !llvm.ptr\n`;
    header += `    %null_ptr = llvm.mlir.zero : !llvm.ptr\n`;
    header += `    %c0_i32 = arith.constant 0 : i32\n`;
    header += `    scf.while : () -> () {\n`;
    header += `      %curr = llvm.load %curr_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %has_curr = llvm.icmp "ne" %curr, %null_ptr : !llvm.ptr\n`;
    header += `      scf.condition(%has_curr)\n`;
    header += `    } do {\n`;
    header += `    ^bb0:\n`;
    header += `      %curr = llvm.load %curr_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %k_ptr = llvm.getelementptr %curr[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `      %curr_key = llvm.load %k_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %cmp = llvm.call @strcmp(%curr_key, %key) : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `      %is_eq = arith.cmpi eq, %cmp, %c0_i32 : i32\n`;
    header += `      scf.if %is_eq {\n`;
    header += `        %v_ptr = llvm.getelementptr %curr[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `        %val = llvm.load %v_ptr : !llvm.ptr -> f64\n`;
    header += `        llvm.store %val, %res_slot : f64, !llvm.ptr\n`;
    header += `        llvm.store %null_ptr, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      } else {\n`;
    header += `        %next_ptr = llvm.getelementptr %curr[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `        %next = llvm.load %next_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `        llvm.store %next, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      }\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %res = llvm.load %res_slot : !llvm.ptr -> f64\n`;
    header += `    func.return %res : f64\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_map_get_str_ptr(%map: !llvm.ptr, %key: !llvm.ptr) -> !llvm.ptr {\n`;
    header += `    %cap_ptr = llvm.getelementptr %map[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    %cap = llvm.load %cap_ptr : !llvm.ptr -> i64\n`;
    header += `    %buckets_ptr = llvm.getelementptr %map[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    %buckets = llvm.load %buckets_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %h = func.call @rts_hash_str(%key) : (!llvm.ptr) -> i64\n`;
    header += `    %b_idx = arith.remui %h, %cap : i64\n`;
    header += `    %bucket_slot = llvm.getelementptr %buckets[%b_idx] : (!llvm.ptr, i64) -> !llvm.ptr, !llvm.ptr\n`;
    header += `    %c1_i32 = arith.constant 1 : i32\n`;
    header += `    %curr_slot = llvm.alloca %c1_i32 x !llvm.ptr : (i32) -> !llvm.ptr\n`;
    header += `    %init_head = llvm.load %bucket_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `    llvm.store %init_head, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `    %res_slot = llvm.alloca %c1_i32 x !llvm.ptr : (i32) -> !llvm.ptr\n`;
    header += `    %null_ptr = llvm.mlir.zero : !llvm.ptr\n`;
    header += `    llvm.store %null_ptr, %res_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `    %c0_i32 = arith.constant 0 : i32\n`;
    header += `    scf.while : () -> () {\n`;
    header += `      %curr = llvm.load %curr_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %has_curr = llvm.icmp "ne" %curr, %null_ptr : !llvm.ptr\n`;
    header += `      scf.condition(%has_curr)\n`;
    header += `    } do {\n`;
    header += `    ^bb0:\n`;
    header += `      %curr = llvm.load %curr_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %k_ptr = llvm.getelementptr %curr[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `      %curr_key = llvm.load %k_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %cmp = llvm.call @strcmp(%curr_key, %key) : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `      %is_eq = arith.cmpi eq, %cmp, %c0_i32 : i32\n`;
    header += `      scf.if %is_eq {\n`;
    header += `        %v_ptr = llvm.getelementptr %curr[0, 3] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `        %val = llvm.load %v_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `        llvm.store %val, %res_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        llvm.store %null_ptr, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      } else {\n`;
    header += `        %next_ptr = llvm.getelementptr %curr[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `        %next = llvm.load %next_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `        llvm.store %next, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      }\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %res = llvm.load %res_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `    func.return %res : !llvm.ptr\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_map_has_str(%map: !llvm.ptr, %key: !llvm.ptr) -> i1 {\n`;
    header += `    %cap_ptr = llvm.getelementptr %map[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    %cap = llvm.load %cap_ptr : !llvm.ptr -> i64\n`;
    header += `    %buckets_ptr = llvm.getelementptr %map[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    %buckets = llvm.load %buckets_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %h = func.call @rts_hash_str(%key) : (!llvm.ptr) -> i64\n`;
    header += `    %b_idx = arith.remui %h, %cap : i64\n`;
    header += `    %bucket_slot = llvm.getelementptr %buckets[%b_idx] : (!llvm.ptr, i64) -> !llvm.ptr, !llvm.ptr\n`;
    header += `    %c1_i32 = arith.constant 1 : i32\n`;
    header += `    %curr_slot = llvm.alloca %c1_i32 x !llvm.ptr : (i32) -> !llvm.ptr\n`;
    header += `    %init_head = llvm.load %bucket_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `    llvm.store %init_head, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `    %res_slot = llvm.alloca %c1_i32 x i1 : (i32) -> !llvm.ptr\n`;
    header += `    %false_val = arith.constant false\n`;
    header += `    llvm.store %false_val, %res_slot : i1, !llvm.ptr\n`;
    header += `    %null_ptr = llvm.mlir.zero : !llvm.ptr\n`;
    header += `    %c0_i32 = arith.constant 0 : i32\n`;
    header += `    scf.while : () -> () {\n`;
    header += `      %curr = llvm.load %curr_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %has_curr = llvm.icmp "ne" %curr, %null_ptr : !llvm.ptr\n`;
    header += `      scf.condition(%has_curr)\n`;
    header += `    } do {\n`;
    header += `    ^bb0:\n`;
    header += `      %curr = llvm.load %curr_slot : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %k_ptr = llvm.getelementptr %curr[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `      %curr_key = llvm.load %k_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `      %cmp = llvm.call @strcmp(%curr_key, %key) : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `      %is_eq = arith.cmpi eq, %cmp, %c0_i32 : i32\n`;
    header += `      scf.if %is_eq {\n`;
    header += `        %true_val = arith.constant true\n`;
    header += `        llvm.store %true_val, %res_slot : i1, !llvm.ptr\n`;
    header += `        llvm.store %null_ptr, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      } else {\n`;
    header += `        %next_ptr = llvm.getelementptr %curr[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, f64, !llvm.ptr)>\n`;
    header += `        %next = llvm.load %next_ptr : !llvm.ptr -> !llvm.ptr\n`;
    header += `        llvm.store %next, %curr_slot : !llvm.ptr, !llvm.ptr\n`;
    header += `        scf.yield\n`;
    header += `      }\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %res = llvm.load %res_slot : !llvm.ptr -> i1\n`;
    header += `    func.return %res : i1\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_map_size(%map: !llvm.ptr) -> i64 {\n`;
    header += `    %sz_ptr = llvm.getelementptr %map[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i64, !llvm.ptr)>\n`;
    header += `    %sz = llvm.load %sz_ptr : !llvm.ptr -> i64\n`;
    header += `    func.return %sz : i64\n`;
    header += `  }\n\n`;

    return header;
  }

  static emitChannels(usedFeatures) {
    if (!usedFeatures.channels) return "";
    let header = "";

    // 1. @rts_chan_new(capacity: i64) -> !llvm.ptr
    header += `  func.func @rts_chan_new(%cap: i64) -> !llvm.ptr {\n`;
    header += `    %c64 = llvm.mlir.constant(64 : i64) : i64\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %c1 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `    %c8 = llvm.mlir.constant(8 : i64) : i64\n`;
    header += `    %null = llvm.mlir.zero : !llvm.ptr\n`;
    header += `    %chan = llvm.call @malloc(%c64) : (i64) -> !llvm.ptr\n`;
    header += `    %mtx = llvm.call @malloc(%c64) : (i64) -> !llvm.ptr\n`;
    header += `    llvm.call @pthread_mutex_init(%mtx, %null) : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `    %p_mtx = llvm.getelementptr %chan[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    llvm.store %mtx, %p_mtx : !llvm.ptr, !llvm.ptr\n`;
    header += `    %cv_r = llvm.call @malloc(%c64) : (i64) -> !llvm.ptr\n`;
    header += `    llvm.call @pthread_cond_init(%cv_r, %null) : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `    %p_cv_r = llvm.getelementptr %chan[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    llvm.store %cv_r, %p_cv_r : !llvm.ptr, !llvm.ptr\n`;
    header += `    %cv_s = llvm.call @malloc(%c64) : (i64) -> !llvm.ptr\n`;
    header += `    llvm.call @pthread_cond_init(%cv_s, %null) : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `    %p_cv_s = llvm.getelementptr %chan[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    llvm.store %cv_s, %p_cv_s : !llvm.ptr, !llvm.ptr\n`;
    header += `    %is_zero = arith.cmpi sle, %cap, %c0 : i64\n`;
    header += `    %real_cap = arith.select %is_zero, %c1, %cap : i64\n`;
    header += `    %buf_bytes = arith.muli %real_cap, %c8 : i64\n`;
    header += `    %buf = llvm.call @malloc(%buf_bytes) : (i64) -> !llvm.ptr\n`;
    header += `    %p_buf = llvm.getelementptr %chan[0, 3] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    llvm.store %buf, %p_buf : !llvm.ptr, !llvm.ptr\n`;
    header += `    %p_head = llvm.getelementptr %chan[0, 4] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    llvm.store %c0, %p_head : i64, !llvm.ptr\n`;
    header += `    %p_tail = llvm.getelementptr %chan[0, 5] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    llvm.store %c0, %p_tail : i64, !llvm.ptr\n`;
    header += `    %p_cnt = llvm.getelementptr %chan[0, 6] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    llvm.store %c0, %p_cnt : i64, !llvm.ptr\n`;
    header += `    %p_cap = llvm.getelementptr %chan[0, 7] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    llvm.store %real_cap, %p_cap : i64, !llvm.ptr\n`;
    header += `    func.return %chan : !llvm.ptr\n`;
    header += `  }\n\n`;

    // 2. @rts_chan_send_f64(chan: !llvm.ptr, val: f64)
    header += `  func.func @rts_chan_send_f64(%chan: !llvm.ptr, %val: f64) {\n`;
    header += `    %c1 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `    %p_mtx = llvm.getelementptr %chan[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %mtx = llvm.load %p_mtx : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %p_cv_s = llvm.getelementptr %chan[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %cv_s = llvm.load %p_cv_s : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %p_cv_r = llvm.getelementptr %chan[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %cv_r = llvm.load %p_cv_r : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %p_buf = llvm.getelementptr %chan[0, 3] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %buf = llvm.load %p_buf : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %p_tail = llvm.getelementptr %chan[0, 5] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %p_cnt = llvm.getelementptr %chan[0, 6] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %p_cap = llvm.getelementptr %chan[0, 7] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %cap = llvm.load %p_cap : !llvm.ptr -> i64\n`;
    header += `    llvm.call @pthread_mutex_lock(%mtx) : (!llvm.ptr) -> i32\n`;
    header += `    scf.while : () -> () {\n`;
    header += `      %cnt = llvm.load %p_cnt : !llvm.ptr -> i64\n`;
    header += `      %full = arith.cmpi sge, %cnt, %cap : i64\n`;
    header += `      scf.condition(%full)\n`;
    header += `    } do {\n`;
    header += `    ^bb0:\n`;
    header += `      llvm.call @pthread_cond_wait(%cv_s, %mtx) : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %tail = llvm.load %p_tail : !llvm.ptr -> i64\n`;
    header += `    %slot = llvm.getelementptr %buf[%tail] : (!llvm.ptr, i64) -> !llvm.ptr, f64\n`;
    header += `    llvm.store %val, %slot : f64, !llvm.ptr\n`;
    header += `    %next_tail = arith.addi %tail, %c1 : i64\n`;
    header += `    %wrap_tail = arith.remui %next_tail, %cap : i64\n`;
    header += `    llvm.store %wrap_tail, %p_tail : i64, !llvm.ptr\n`;
    header += `    %cnt_now = llvm.load %p_cnt : !llvm.ptr -> i64\n`;
    header += `    %new_cnt = arith.addi %cnt_now, %c1 : i64\n`;
    header += `    llvm.store %new_cnt, %p_cnt : i64, !llvm.ptr\n`;
    header += `    llvm.call @pthread_cond_signal(%cv_r) : (!llvm.ptr) -> i32\n`;
    header += `    llvm.call @pthread_mutex_unlock(%mtx) : (!llvm.ptr) -> i32\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    // 3. @rts_chan_recv_f64(chan: !llvm.ptr) -> f64
    header += `  func.func @rts_chan_recv_f64(%chan: !llvm.ptr) -> f64 {\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %c1 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `    %p_mtx = llvm.getelementptr %chan[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %mtx = llvm.load %p_mtx : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %p_cv_r = llvm.getelementptr %chan[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %cv_r = llvm.load %p_cv_r : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %p_cv_s = llvm.getelementptr %chan[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %cv_s = llvm.load %p_cv_s : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %p_buf = llvm.getelementptr %chan[0, 3] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %buf = llvm.load %p_buf : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %p_head = llvm.getelementptr %chan[0, 4] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %p_cnt = llvm.getelementptr %chan[0, 6] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %p_cap = llvm.getelementptr %chan[0, 7] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr, i64, i64, i64, i64)>\n`;
    header += `    %cap = llvm.load %p_cap : !llvm.ptr -> i64\n`;
    header += `    llvm.call @pthread_mutex_lock(%mtx) : (!llvm.ptr) -> i32\n`;
    header += `    scf.while : () -> () {\n`;
    header += `      %cnt = llvm.load %p_cnt : !llvm.ptr -> i64\n`;
    header += `      %empty = arith.cmpi eq, %cnt, %c0 : i64\n`;
    header += `      scf.condition(%empty)\n`;
    header += `    } do {\n`;
    header += `    ^bb0:\n`;
    header += `      llvm.call @pthread_cond_wait(%cv_r, %mtx) : (!llvm.ptr, !llvm.ptr) -> i32\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %head = llvm.load %p_head : !llvm.ptr -> i64\n`;
    header += `    %slot = llvm.getelementptr %buf[%head] : (!llvm.ptr, i64) -> !llvm.ptr, f64\n`;
    header += `    %val = llvm.load %slot : !llvm.ptr -> f64\n`;
    header += `    %next_head = arith.addi %head, %c1 : i64\n`;
    header += `    %wrap_head = arith.remui %next_head, %cap : i64\n`;
    header += `    llvm.store %wrap_head, %p_head : i64, !llvm.ptr\n`;
    header += `    %cnt_now = llvm.load %p_cnt : !llvm.ptr -> i64\n`;
    header += `    %new_cnt = arith.subi %cnt_now, %c1 : i64\n`;
    header += `    llvm.store %new_cnt, %p_cnt : i64, !llvm.ptr\n`;
    header += `    llvm.call @pthread_cond_signal(%cv_s) : (!llvm.ptr) -> i32\n`;
    header += `    llvm.call @pthread_mutex_unlock(%mtx) : (!llvm.ptr) -> i32\n`;
    header += `    func.return %val : f64\n`;
    header += `  }\n\n`;

    return header;
  }

  static emitAllocators(usedFeatures) {
    if (!usedFeatures.allocators) return "";
    let header = "";

    // 1. ARENA ALLOCATOR (!llvm.struct<(!llvm.ptr, i64, i64)>: buffer, capacity, offset)
    header += `  func.func @rts_arena_new(%cap: i64) -> !llvm.ptr {\n`;
    header += `    %c24 = llvm.mlir.constant(24 : i64) : i64\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %c1024 = llvm.mlir.constant(1024 : i64) : i64\n`;
    header += `    %is_le = arith.cmpi sle, %cap, %c0 : i64\n`;
    header += `    %real_cap = arith.select %is_le, %c1024, %cap : i64\n`;
    header += `    %arena = llvm.call @malloc(%c24) : (i64) -> !llvm.ptr\n`;
    header += `    %buf = llvm.call @malloc(%real_cap) : (i64) -> !llvm.ptr\n`;
    header += `    %p_buf = llvm.getelementptr %arena[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    llvm.store %buf, %p_buf : !llvm.ptr, !llvm.ptr\n`;
    header += `    %p_cap = llvm.getelementptr %arena[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    llvm.store %real_cap, %p_cap : i64, !llvm.ptr\n`;
    header += `    %p_off = llvm.getelementptr %arena[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    llvm.store %c0, %p_off : i64, !llvm.ptr\n`;
    header += `    func.return %arena : !llvm.ptr\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_arena_alloc(%arena: !llvm.ptr, %size: i64) -> !llvm.ptr {\n`;
    header += `    %c7 = llvm.mlir.constant(7 : i64) : i64\n`;
    header += `    %c_mask = llvm.mlir.constant(-8 : i64) : i64\n`;
    header += `    %s1 = arith.addi %size, %c7 : i64\n`;
    header += `    %aligned_sz = arith.andi %s1, %c_mask : i64\n`;
    header += `    %p_buf = llvm.getelementptr %arena[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    %buf = llvm.load %p_buf : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %p_cap = llvm.getelementptr %arena[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    %cap = llvm.load %p_cap : !llvm.ptr -> i64\n`;
    header += `    %p_off = llvm.getelementptr %arena[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    %off = llvm.load %p_off : !llvm.ptr -> i64\n`;
    header += `    %new_off = arith.addi %off, %aligned_sz : i64\n`;
    header += `    %overflow = arith.cmpi ugt, %new_off, %cap : i64\n`;
    header += `    scf.if %overflow {\n`;
    header += `      llvm.call @abort() : () -> ()\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %res = llvm.getelementptr %buf[%off] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `    llvm.store %new_off, %p_off : i64, !llvm.ptr\n`;
    header += `    func.return %res : !llvm.ptr\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_arena_reset(%arena: !llvm.ptr) {\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %p_off = llvm.getelementptr %arena[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    llvm.store %c0, %p_off : i64, !llvm.ptr\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_arena_destroy(%arena: !llvm.ptr) {\n`;
    header += `    %p_buf = llvm.getelementptr %arena[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    %buf = llvm.load %p_buf : !llvm.ptr -> !llvm.ptr\n`;
    header += `    llvm.call @free(%buf) : (!llvm.ptr) -> ()\n`;
    header += `    llvm.call @free(%arena) : (!llvm.ptr) -> ()\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    // 2. POOL ALLOCATOR (!llvm.struct<(!llvm.ptr, !llvm.ptr, i64, i64)>: buffer, free_list_head, chunk_sz, chunk_cnt)
    header += `  func.func @rts_pool_new(%chunk_sz: i64, %chunk_cnt: i64) -> !llvm.ptr {\n`;
    header += `    %c32 = llvm.mlir.constant(32 : i64) : i64\n`;
    header += `    %c8 = llvm.mlir.constant(8 : i64) : i64\n`;
    header += `    %c7 = llvm.mlir.constant(7 : i64) : i64\n`;
    header += `    %c_mask = llvm.mlir.constant(-8 : i64) : i64\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %c1 = llvm.mlir.constant(1 : i64) : i64\n`;
    header += `    %s1 = arith.addi %chunk_sz, %c7 : i64\n`;
    header += `    %aligned_sz = arith.andi %s1, %c_mask : i64\n`;
    header += `    %is_sz_small = arith.cmpi slt, %aligned_sz, %c8 : i64\n`;
    header += `    %real_sz = arith.select %is_sz_small, %c8, %aligned_sz : i64\n`;
    header += `    %total_bytes = arith.muli %real_sz, %chunk_cnt : i64\n`;
    header += `    %pool = llvm.call @malloc(%c32) : (i64) -> !llvm.ptr\n`;
    header += `    %buf = llvm.call @malloc(%total_bytes) : (i64) -> !llvm.ptr\n`;
    header += `    %p_buf = llvm.getelementptr %pool[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, i64, i64)>\n`;
    header += `    llvm.store %buf, %p_buf : !llvm.ptr, !llvm.ptr\n`;
    header += `    %p_head = llvm.getelementptr %pool[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, i64, i64)>\n`;
    header += `    llvm.store %buf, %p_head : !llvm.ptr, !llvm.ptr\n`;
    header += `    %p_sz = llvm.getelementptr %pool[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, i64, i64)>\n`;
    header += `    llvm.store %real_sz, %p_sz : i64, !llvm.ptr\n`;
    header += `    %p_cnt = llvm.getelementptr %pool[0, 3] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, i64, i64)>\n`;
    header += `    llvm.store %chunk_cnt, %p_cnt : i64, !llvm.ptr\n`;
    header += `    %c1_i32 = arith.constant 1 : i32\n`;
    header += `    %idx_slot = llvm.alloca %c1_i32 x i64 : (i32) -> !llvm.ptr\n`;
    header += `    llvm.store %c0, %idx_slot : i64, !llvm.ptr\n`;
    header += `    %last_idx = arith.subi %chunk_cnt, %c1 : i64\n`;
    header += `    scf.while : () -> () {\n`;
    header += `      %i = llvm.load %idx_slot : !llvm.ptr -> i64\n`;
    header += `      %cond = arith.cmpi slt, %i, %last_idx : i64\n`;
    header += `      scf.condition(%cond)\n`;
    header += `    } do {\n`;
    header += `    ^bb0:\n`;
    header += `      %i = llvm.load %idx_slot : !llvm.ptr -> i64\n`;
    header += `      %byte_off = arith.muli %i, %real_sz : i64\n`;
    header += `      %curr_chunk = llvm.getelementptr %buf[%byte_off] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      %next_i = arith.addi %i, %c1 : i64\n`;
    header += `      %next_byte_off = arith.muli %next_i, %real_sz : i64\n`;
    header += `      %next_chunk = llvm.getelementptr %buf[%next_byte_off] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `      llvm.store %next_chunk, %curr_chunk : !llvm.ptr, !llvm.ptr\n`;
    header += `      llvm.store %next_i, %idx_slot : i64, !llvm.ptr\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %null_ptr = llvm.mlir.zero : !llvm.ptr\n`;
    header += `    %last_byte_off = arith.muli %last_idx, %real_sz : i64\n`;
    header += `    %last_chunk = llvm.getelementptr %buf[%last_byte_off] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `    llvm.store %null_ptr, %last_chunk : !llvm.ptr, !llvm.ptr\n`;
    header += `    func.return %pool : !llvm.ptr\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_pool_alloc(%pool: !llvm.ptr) -> !llvm.ptr {\n`;
    header += `    %p_head = llvm.getelementptr %pool[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, i64, i64)>\n`;
    header += `    %head = llvm.load %p_head : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %null_ptr = llvm.mlir.zero : !llvm.ptr\n`;
    header += `    %is_null = llvm.icmp "eq" %head, %null_ptr : !llvm.ptr\n`;
    header += `    scf.if %is_null {\n`;
    header += `      llvm.call @abort() : () -> ()\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %next = llvm.load %head : !llvm.ptr -> !llvm.ptr\n`;
    header += `    llvm.store %next, %p_head : !llvm.ptr, !llvm.ptr\n`;
    header += `    func.return %head : !llvm.ptr\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_pool_free(%pool: !llvm.ptr, %chunk: !llvm.ptr) {\n`;
    header += `    %p_head = llvm.getelementptr %pool[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, i64, i64)>\n`;
    header += `    %curr_head = llvm.load %p_head : !llvm.ptr -> !llvm.ptr\n`;
    header += `    llvm.store %curr_head, %chunk : !llvm.ptr, !llvm.ptr\n`;
    header += `    llvm.store %chunk, %p_head : !llvm.ptr, !llvm.ptr\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_pool_destroy(%pool: !llvm.ptr) {\n`;
    header += `    %p_buf = llvm.getelementptr %pool[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, !llvm.ptr, i64, i64)>\n`;
    header += `    %buf = llvm.load %p_buf : !llvm.ptr -> !llvm.ptr\n`;
    header += `    llvm.call @free(%buf) : (!llvm.ptr) -> ()\n`;
    header += `    llvm.call @free(%pool) : (!llvm.ptr) -> ()\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    // 3. FIXED BUFFER ALLOCATOR (!llvm.struct<(!llvm.ptr, i64, i64)>: buffer, capacity, offset)
    header += `  func.func @rts_fixed_buffer_new(%cap: i64) -> !llvm.ptr {\n`;
    header += `    %c24 = llvm.mlir.constant(24 : i64) : i64\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %fb = llvm.call @malloc(%c24) : (i64) -> !llvm.ptr\n`;
    header += `    %buf = llvm.call @malloc(%cap) : (i64) -> !llvm.ptr\n`;
    header += `    %p_buf = llvm.getelementptr %fb[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    llvm.store %buf, %p_buf : !llvm.ptr, !llvm.ptr\n`;
    header += `    %p_cap = llvm.getelementptr %fb[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    llvm.store %cap, %p_cap : i64, !llvm.ptr\n`;
    header += `    %p_off = llvm.getelementptr %fb[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    llvm.store %c0, %p_off : i64, !llvm.ptr\n`;
    header += `    func.return %fb : !llvm.ptr\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_fixed_buffer_alloc(%fb: !llvm.ptr, %size: i64) -> !llvm.ptr {\n`;
    header += `    %c7 = llvm.mlir.constant(7 : i64) : i64\n`;
    header += `    %c_mask = llvm.mlir.constant(-8 : i64) : i64\n`;
    header += `    %s1 = arith.addi %size, %c7 : i64\n`;
    header += `    %aligned_sz = arith.andi %s1, %c_mask : i64\n`;
    header += `    %p_buf = llvm.getelementptr %fb[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    %buf = llvm.load %p_buf : !llvm.ptr -> !llvm.ptr\n`;
    header += `    %p_cap = llvm.getelementptr %fb[0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    %cap = llvm.load %p_cap : !llvm.ptr -> i64\n`;
    header += `    %p_off = llvm.getelementptr %fb[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    %off = llvm.load %p_off : !llvm.ptr -> i64\n`;
    header += `    %new_off = arith.addi %off, %aligned_sz : i64\n`;
    header += `    %overflow = arith.cmpi ugt, %new_off, %cap : i64\n`;
    header += `    scf.if %overflow {\n`;
    header += `      llvm.call @abort() : () -> ()\n`;
    header += `      scf.yield\n`;
    header += `    }\n`;
    header += `    %res = llvm.getelementptr %buf[%off] : (!llvm.ptr, i64) -> !llvm.ptr, i8\n`;
    header += `    llvm.store %new_off, %p_off : i64, !llvm.ptr\n`;
    header += `    func.return %res : !llvm.ptr\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_fixed_buffer_reset(%fb: !llvm.ptr) {\n`;
    header += `    %c0 = llvm.mlir.constant(0 : i64) : i64\n`;
    header += `    %p_off = llvm.getelementptr %fb[0, 2] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    llvm.store %c0, %p_off : i64, !llvm.ptr\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    header += `  func.func @rts_fixed_buffer_destroy(%fb: !llvm.ptr) {\n`;
    header += `    %p_buf = llvm.getelementptr %fb[0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(!llvm.ptr, i64, i64)>\n`;
    header += `    %buf = llvm.load %p_buf : !llvm.ptr -> !llvm.ptr\n`;
    header += `    llvm.call @free(%buf) : (!llvm.ptr) -> ()\n`;
    header += `    llvm.call @free(%fb) : (!llvm.ptr) -> ()\n`;
    header += `    func.return\n`;
    header += `  }\n\n`;

    return header;
  }

  static emitAll(builder, isWasm, needsHeap) {
    let header = "";
    if (isWasm && needsHeap) {
      header += this.emitWasmHeap(builder.usedFeatures);
    }
    header += this.emitStrings(builder.usedFeatures);
    header += this.emitPrintf(builder.usedFeatures, builder.symTrue, builder.symFalse);
    header += this.emitUnion(
      builder.usedFeatures,
      builder.symNumber,
      builder.symString,
      builder.symBoolean,
      builder.symObject
    );
    header += this.emitMapSet(builder.usedFeatures);
    header += this.emitChannels(builder.usedFeatures);
    header += this.emitAllocators(builder.usedFeatures);
    return header;
  }
}
